version: 2

models:
  - name: silver_customers
    description: "Customer data cleaned and deduplicated"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: silver_devices
    description: "devices data clean"
    columns:
      - name: device_id
        tests:
          - not_null
          - unique

  - name: silver_locations
    description: "location data clean"
    columns:
      - name: location_id
        tests:
          - not_null
          - unique

  - name: silver_services
    description: "unique services"
    columns:
      - name: service_id
        tests:
          - not_null
          - unique
